In [1]:
import numpy as np

In [48]:
def sigmoide(z):
    return 1 / (1 + np.exp(-z))

In [57]:
X = np.array([-5, 6, 1])

In [58]:
a1 = np.append(np.array(1), X)
a1

array([ 1, -5,  6,  1])

In [59]:
Theta1 = np.random.randn(4,3)
print Theta1
Theta2 = np.random.randn(1, 4)
print Theta2

[[-0.76061094  0.24812318 -0.16154468]
 [-2.94625241  0.36685123 -0.46882847]
 [-0.8570486   0.22023111 -1.13144862]
 [-1.9113305  -1.38137695 -0.07225834]]
[[-0.95904712 -0.57177558 -0.9440629  -0.76385543]]


In [60]:
z2 = a1.dot(Theta1)
z2

array([ 6.91702904, -1.64612326, -4.67835235])

In [61]:
a2 = np.append(np.array(1), sigmoide(z2))
print a2

[ 1.          0.99901021  0.16163359  0.00920873]


In [62]:
z3 = a2.dot(Theta2.T)
z3

array([-1.68988317])

In [63]:
hx = sigmoide(z3)
hx

array([ 0.15579121])